language: go
dist: xenial
env:
  - GO111MODULE=on
  - CODECOV_TOKEN="2d448476-b34b-4e7e-a7f7-5fe9b1806366"
script:  go test --race --coverprofile=coverage.txt --covermode=atomic ./...
after_success: bash <(curl -s https://codecov.io/bash)
go:
  - 1.13.x
  - 1.14.x
